# Generated by Django 5.0.7 on 2024-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFollowing',
            field=models.BooleanField(default=False),
        ),
    ]
