# Generated by Django 5.0.7 on 2024-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_isfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isFollowing',
        ),
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(related_name='likes', to='network.post'),
        ),
    ]
