# Generated by Django 5.0.7 on 2024-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_isfollowing_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedBy',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
